import type {
  PortfolioAccountDto,
  PortfolioContextDto,
  PortfolioFundExposureDto,
  PortfolioPositionDto,
  PortfolioWatchThemeDto,
} from '../presentation/dto/portfolio.dto';

const fallbackPositions: readonly PortfolioPositionDto[] = [
  {
    id: 'fallback-position-600366',
    symbol: '600366',
    name: '宁波韵升',
    quantity: 800,
    costPrice: '13.470000',
    latestPrice: null,
    marketValue: null,
    unrealizedPnl: null,
    themeTags: ['机器人 / 物理 AI', '新材料 / 磁材'],
    thesisSummary: '物理 AI 与机器人链条观察标的，后续需要用行情强弱和主题延续性验证。',
    actionBias: 'hold',
    riskLevel: 'medium',
    notes: null,
  },
  {
    id: 'fallback-position-601689',
    symbol: '601689',
    name: '拓普集团',
    quantity: 200,
    costPrice: '69.620000',
    latestPrice: null,
    marketValue: null,
    unrealizedPnl: null,
    themeTags: ['机器人 / 物理 AI', '汽车零部件'],
    thesisSummary: '机器人和智能汽车弹性方向，重点跟踪主题拥挤度与趋势质量。',
    actionBias: 'hold',
    riskLevel: 'medium',
    notes: null,
  },
  {
    id: 'fallback-position-002031',
    symbol: '002031',
    name: '巨轮智能',
    quantity: 2100,
    costPrice: '8.132900',
    latestPrice: null,
    marketValue: null,
    unrealizedPnl: null,
    themeTags: ['机器人 / 物理 AI', '智能装备'],
    thesisSummary: '高弹性机器人方向，已在跌停后 7.54 补仓 600 股，后续更需要用风控条件约束。',
    actionBias: 'watch',
    riskLevel: 'high',
    notes: null,
  },
  {
    id: 'fallback-position-002714',
    symbol: '002714',
    name: '牧原股份',
    quantity: 100,
    costPrice: '44.670000',
    latestPrice: null,
    marketValue: null,
    unrealizedPnl: null,
    themeTags: ['消费', '农牧周期'],
    thesisSummary: '非 AI 主线的周期/消费平衡仓，关注猪周期和组合分散价值。',
    actionBias: 'hold',
    riskLevel: 'medium',
    notes: null,
  },
  {
    id: 'fallback-position-603005',
    symbol: '603005',
    name: '晶方科技',
    quantity: 300,
    costPrice: '38.397000',
    latestPrice: null,
    marketValue: null,
    unrealizedPnl: null,
    themeTags: ['半导体', 'AI 硬件', '先进封装'],
    thesisSummary: 'AI 硬件和半导体链条观察仓，后续需要结合半导体主题强弱、估值和趋势质量决定是否继续加仓。',
    actionBias: 'watch',
    riskLevel: 'medium',
    notes: null,
  },
];

const fallbackFundExposures: readonly PortfolioFundExposureDto[] = [
  { id: 'fallback-fund-nasdaq100', name: '纳指100', fundCode: null, theme: '海外科技', amount: '33910.00', weightPercent: '23.93', actionBias: 'hold', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-communication', name: '通信设备', fundCode: null, theme: '通信设备 / CPO', amount: '21137.00', weightPercent: '14.91', actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-digital-tech', name: '数字经济 / 大科技', fundCode: null, theme: '数字经济 / 大科技', amount: '19320.00', weightPercent: '13.63', actionBias: 'hold', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-gold', name: '黄金', fundCode: null, theme: '黄金 / 避险', amount: '16017.00', weightPercent: '11.30', actionBias: 'hold', riskLevel: 'low', notes: null },
  { id: 'fallback-fund-csi1000', name: '中证1000', fundCode: null, theme: '中证1000 / 小盘风格', amount: '14516.00', weightPercent: '10.24', actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-ai', name: '人工智能', fundCode: null, theme: 'AI / 人工智能', amount: '13301.00', weightPercent: '9.38', actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-green-power', name: '绿电', fundCode: null, theme: '绿电 / 新能源', amount: '8960.00', weightPercent: '6.32', actionBias: 'risk_control', riskLevel: 'high', notes: null },
  { id: 'fallback-fund-consumption', name: '消费', fundCode: null, theme: '消费', amount: '2747.00', weightPercent: '1.94', actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-hstech', name: '恒生科技', fundCode: null, theme: '港股科技', amount: '2307.00', weightPercent: '1.63', actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-global', name: '全球精选', fundCode: null, theme: '全球权益', amount: '2029.00', weightPercent: '1.43', actionBias: 'hold', riskLevel: 'medium', notes: null },
  { id: 'fallback-fund-sp500', name: '标普500', fundCode: null, theme: '海外宽基', amount: '1142.00', weightPercent: '0.81', actionBias: 'hold', riskLevel: 'medium', notes: null },
];

const fallbackWatchThemes: readonly PortfolioWatchThemeDto[] = [
  { id: 'fallback-watch-physical-ai', name: '物理 AI', category: 'AI', priority: 100, actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-watch-robot', name: '机器人', category: 'AI', priority: 95, actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-watch-ai-etf', name: 'AI ETF', category: 'AI', priority: 90, actionBias: 'build', riskLevel: 'medium', notes: null },
  { id: 'fallback-watch-cpo', name: '通信设备 / CPO', category: 'AI 算力', priority: 85, actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-watch-gold', name: '黄金', category: '避险', priority: 70, actionBias: 'hold', riskLevel: 'low', notes: null },
  { id: 'fallback-watch-csi1000', name: '中证1000', category: '宽基', priority: 65, actionBias: 'watch', riskLevel: 'medium', notes: null },
  { id: 'fallback-watch-green-power', name: '绿电', category: '新能源', priority: 50, actionBias: 'risk_control', riskLevel: 'high', notes: null },
  { id: 'fallback-watch-hstech', name: '恒生科技', category: '港股科技', priority: 45, actionBias: 'watch', riskLevel: 'medium', notes: null },
];

const fallbackAccount: PortfolioAccountDto = {
  id: 'fallback-account-ricki',
  name: 'Ricki A股账户 + 可见基金持仓',
  accountType: 'MIXED',
  baseCurrency: 'CNY',
  totalAssetValue: '141737.00',
  cashValue: null,
  visibleAssetValue: '135386.00',
  description: 'Fallback portfolio context built from Ricki current stock and fund holdings.',
};

export const fallbackPortfolioContext: PortfolioContextDto = {
  source: 'fallback',
  owner: 'Ricki',
  accountScope: 'A 股账户 + 可见基金持仓',
  account: fallbackAccount,
  summary: {
    stockCostValue: '57765.19',
    visibleFundValue: '135386.00',
    knownPortfolioValue: '193151.19',
    stockWeightPercent: '29.91',
    fundWeightPercent: '70.09',
  },
  positions: fallbackPositions,
  fundExposures: fallbackFundExposures,
  marketSnapshots: [],
  watchThemes: fallbackWatchThemes,
  riskFlags: [
    '基金侧海外科技 + 通信设备 + 数字经济 + 人工智能暴露较集中，退潮时会放大波动。',
    '股票侧机器人/物理 AI 与 AI 硬件相关标的较多，个股成本权重接近已知组合三成。',
    '绿电暴露当前应降低加仓优先级，等待趋势或催化修复。',
  ],
  actionRules: [
    '没有真实行情和主题强弱确认前，默认观察，不主动追高。',
    '半仓不到时可以寻找分批加仓点，但必须优先检查主题拥挤度和组合集中度。',
    '任何加仓建议必须同时给出触发条件、反证条件和风控条件。',
  ],
};
